apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ${{ values.component_id }}-system
  description: System for ${{ values.component_id }}
spec:
  owner: ${{ values.owner }}
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.component_id }}-api
  description: API for ${{ values.component_id }}
spec:
  type: openapi
  lifecycle: ${{ values.lifecycle | default("experimental") }}
  owner: ${{ values.owner }}
  system: ${{ values.component_id }}-system
  definition: |
    openapi: 3.0.0
    info:
      title: ${{ values.component_id | title }} API
      version: 1.0.0
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.component_id }}-database
  description: Database for ${{ values.component_id }}
spec:
  type: database
  owner: ${{ values.owner }}
  system: ${{ values.component_id }}-system
